name: bledetect101
version: 4.5
summary: bluetooth detect tool
description: |
  Bluetooth detection tool

grade: stable
architectures:
  - build-on: [armhf]
    run-on: [armhf]

parts:
  bledetect:
    plugin: make
    source: src
    build-packages:
      - build-essential
      - gcc
      - make
      - libbluetooth-dev
    stage-packages:
      - libbluetooth-dev
apps:
  bledetect-cli:
    command: bledetect
    plugs: &plugs [network, network-control, bluetooth-control]
